name: xampspvp
version: 2.2
main: br.poa.zambiasi.xampspvp.Main
author: xampS
commands:
   build:
   score:
   checar:
   rank:
   tag:
   lag:
   setar:
   cc:
   chat:
   spawn:
   admin:
   sc:
   staffchat:
   gm:
   invsee:
   tpall:
   fly:
   tp:
   tphere:
   pvp:
   1v1:
   money:
   resetkdr:
   xp:
   arena:
   recraft:
   discord:
   vip:
   tell:
   anuncio:
   lobby: